version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  flower:
    image: mher/flower
    command: --port=5555 --broker=amqp://rabbitmq:5672
    ports:
      - "5555:5555"
  rabbitmq:
    image: "rabbitmq:3.7.8-alpine"
    volumes:
      - rabbitmqdb:/var/lib/rabbitmq
    hostname: rabbitmq
  backend:
    build:
      context: ./backend
      args:
        mode: dev
    command: python3 manage.py runserver 0.0.0.0:3001
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.dev
      - ENV=dev
    volumes:
      - ./backend:/code
      - /tmp/cnap:/transient
    ports:
      - "3001:3001"
    depends_on:
      - db
  celery:
    build:
      context: ./backend
      args:
        mode: dev
    command: celery -A global.celery_config:app worker -l info --logfile='/transient/logs/celery.log' --concurrency=20
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.dev
      - ENV=dev
    volumes:
      - ./backend:/code
      - /tmp/cnap:/transient
    depends_on:
      - db
      - rabbitmq
  celery-beat:
    build:
      context: ./backend
      args:
        mode: dev
    command: sh -c 'rm celerybeat.pid; celery -A global.celery_config:app beat -l info'
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.dev
      - ENV=dev
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - rabbitmq

volumes:
  db_data:
  rabbitmqdb:
